### ISSUE TITLE
Implement new and improve search results designs

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/to-search#5]
See attached screenshot of critical front end changes.
Changes to side bar filters:
- Add bg colour, separator bars and expandable toggles 
Changes to filtering options:
- Sort by drop down - position and styling
- List view and map view toggles

Screenshot - Side bar:
![Screenshot 2019-09-13 at 11 39 48](https://user-images.githubusercontent.com/31090573/64853509-cccda100-d61b-11e9-8b31-68af0d0164f4.png)
Screenshot - Sort by and list vs map toggles:
![Screenshot 2019-09-13 at 11 40 14](https://user-images.githubusercontent.com/31090573/64853506-cc350a80-d61b-11e9-8484-14b0f9e8c24d.png)

Screenshot - Full:
![Screenshot 2019-09-13 at 11 40 06](https://user-images.githubusercontent.com/31090573/64853507-cccda100-d61b-11e9-8678-05d2d7d0ac50.png)

**Comment by viscosho** [comment]
New functionality on this Issue:

Dev - Improving search styles. (spacing, background colors, filter options)
Dev - Adding filter number to search results on mobile.
Dev - Adding search bar to mobile.
Fix - Restricted the post type labels to the global search only.
Fix - Improving footer bar.
Dev - Cosmetic improvements to Search  (spacing, background colors, filter options, labels)
Dev - Making the layout for search independent from the archive layouts.
Dev - Adding collapsible facets option.

**Comment by ashleyshaw** [comment]
@garthglaum please take a look at the outcomes of this enhancement and grab some notes for our release announcement.
